- name: print variable
  hosts: web
  vars:
    COURSE: "DEVOPS WITH AWS"
    DURATION: "120 HOURS"
    TRAINER: "SHIVA KUMAR"
  tasks:
  - name:  Print the name of variable 
     ansible.builtin.debug:
       msg: "hi i am Learning {{COURSE}},URATION,by {{RAINER}} "

